/**
 * exercises.js — Bob's chore list.
 *
 * Each chore has:
 *   id        unique slug (used for localStorage)
 *   tier      1..6 (Bob's week: Day 1..Day 6, growing difficulty)
 *   title     story title
 *   tagline   one-line teaser for the card
 *   icon      material-symbols icon name
 *   topics    study-topic chips shown under the title
 *   funcName  the function the player must implement
 *   stub      starter code shown in the editor
 *   story     array of paragraphs (the subject, Bob-flavored)
 *   signature the required def line
 *   rules     array of bullet rules
 *   examples  [{ input, output }] — shown in the subject
 *   tests     [{ call, args, expected }] — args/expected are PYTHON literals
 *             evaluated inside the Pyodide grader; `call` is display-only.
 *   banned    optional { names: [...], attrs: [...] } — function calls the
 *             robot rejects via AST inspection before running any test.
 */

export const TIERS = [
  { tier: 1, label: "Day 1", subtitle: "Seeds & Scribbles" },
  { tier: 2, label: "Day 2", subtitle: "Pantry Puzzles" },
  { tier: 3, label: "Day 3", subtitle: "Letters & Ladders" },
  { tier: 4, label: "Day 4", subtitle: "Market Day" },
  { tier: 5, label: "Day 5", subtitle: "Fences & Feathers" },
  { tier: 6, label: "Day 6", subtitle: "Secret Codes" },
];

export const EXERCISES = [
  // -----------------------------------------------------------------------
  // DAY 1
  // -----------------------------------------------------------------------
  {
    id: "seed-packet-sort",
    tier: 1,
    title: "The Seed Packet Sort",
    tagline: "Bob's seed drawer is chaos. Sort the packets his very own way.",
    icon: "eco",
    funcName: "seed_packet_sort",
    topics: ["Custom Sort", "Sorting Algorithms"],
    stub: "def seed_packet_sort(labels: list[str]) -> list[str]:\n    pass\n",
    story: [
      "Bob's seed drawer is a mess of little paper packets, each labeled with the name of a plant. Spring is coming and he wants them lined up on the shelf in his very specific Bob-order.",
      "Bob's order goes like this: shortest labels first, because short plants go on the sunny edge. If two labels have the same length, alphabetical order wins — but Bob refuses to care about capital letters when comparing. If they're still tied, the label with FEWER vowels goes first (Bob finds vowels showy). And if two packets are STILL tied after all that, Bob simply keeps them in the order they had in the drawer — no funny business.",
      "One more thing: Bob's robot helper is watching, and it will REFUSE to grade any solution that uses Python's built-in sorted() or the list.sort() method. Bob says sorting is a life skill — do it by hand.",
    ],
    signature: "def seed_packet_sort(labels: list[str]) -> list[str]:",
    rules: [
      "Sort by label length, shortest first",
      "Same length: alphabetical order, comparing letters case-insensitively",
      "Still tied: fewer vowels first (ignore non-letters when counting vowels)",
      "Still tied after ALL of that: keep the original relative order (stable sort)",
      "Handle empty labels and empty lists",
      "FORBIDDEN: using sorted() or list.sort() — the robot checks and rejects them",
    ],
    examples: [
      {
        input: 'seed_packet_sort(["apple", "cat", "banana", "dog", "elephant"])',
        output: "['cat', 'dog', 'apple', 'banana', 'elephant']",
        note: "shortest first, then alphabetical",
      },
      {
        input: 'seed_packet_sort(["aaa", "bbb", "AAA", "BBB"])',
        output: "['aaa', 'AAA', 'bbb', 'BBB']",
        note: "case-insensitive tie, same vowels — the drawer order is kept",
      },
      {
        input: 'seed_packet_sort(["Bb", "bb", "BB"])',
        output: "['Bb', 'bb', 'BB']",
        note: "Titlecase, lowercase, UPPERCASE: all tied, so original order wins",
      },
      {
        input: 'seed_packet_sort(["hello", "world", "hi", "test"])',
        output: "['hi', 'test', 'hello', 'world']",
      },
      { input: "seed_packet_sort([])", output: "[]" },
      { input: 'seed_packet_sort([""])', output: "['']" },
    ],
    tests: [
      { call: 'seed_packet_sort(["apple", "cat", "banana", "dog", "elephant"])', args: "(['apple', 'cat', 'banana', 'dog', 'elephant'],)", expected: "['cat', 'dog', 'apple', 'banana', 'elephant']" },
      { call: 'seed_packet_sort(["aaa", "bbb", "AAA", "BBB"])', args: "(['aaa', 'bbb', 'AAA', 'BBB'],)", expected: "['aaa', 'AAA', 'bbb', 'BBB']" },
      { call: 'seed_packet_sort(["Bb", "bb", "BB"])', args: "(['Bb', 'bb', 'BB'],)", expected: "['Bb', 'bb', 'BB']" },
      { call: 'seed_packet_sort(["hello", "world", "hi", "test"])', args: "(['hello', 'world', 'hi', 'test'],)", expected: "['hi', 'test', 'hello', 'world']" },
      { call: "seed_packet_sort([])", args: "([],)", expected: "[]" },
      { call: 'seed_packet_sort([""])', args: "([''],)", expected: "['']" },
      { call: 'seed_packet_sort(["z", "a", "m"])', args: "(['z', 'a', 'm'],)", expected: "['a', 'm', 'z']" },
      { call: 'seed_packet_sort(["bb", "Aa"])', args: "(['bb', 'Aa'],)", expected: "['Aa', 'bb']" },
      { call: 'seed_packet_sort(["Banana", "banana"])', args: "(['Banana', 'banana'],)", expected: "['Banana', 'banana']" },
      { call: 'seed_packet_sort(["c", "bb", "aaa"])', args: "(['c', 'bb', 'aaa'],)", expected: "['c', 'bb', 'aaa']" },
      { call: 'seed_packet_sort(["dog", "cat", "Dog"])', args: "(['dog', 'cat', 'Dog'],)", expected: "['cat', 'dog', 'Dog']" },
      { call: 'seed_packet_sort(["ab", "a b"])', args: "(['ab', 'a b'],)", expected: "['ab', 'a b']" },
      { call: 'seed_packet_sort(["B", "a"])', args: "(['B', 'a'],)", expected: "['a', 'B']" },
    ],
    banned: { names: ["sorted"], attrs: ["sort"] },
  },
  {
    id: "shared-letters",
    tier: 3,
    title: "Two Shopping Notes",
    tagline: "Which letters show up in BOTH of Bob's scribbled notes?",
    icon: "compare",
    funcName: "shared_letters",
    topics: ["String Intersection", "Sets"],
    stub: "def shared_letters(note_a: str, note_b: str) -> str:\n    pass\n",
    story: [
      "Bob writes shopping notes on scraps of paper and always loses one of them. This week he found two notes in different coat pockets and wants to know which letters appear in BOTH — maybe that will jog his memory about what he meant to buy.",
      "Given the two notes, return a string with every character that appears in both of them, without repetitions, in the order they first appear in the FIRST note.",
    ],
    signature: "def shared_letters(note_a: str, note_b: str) -> str:",
    rules: [
      "Return characters present in both strings",
      "No repetitions in the result",
      "Keep the order in which characters appear in the first string",
      "Handle empty strings (the result is empty)",
      "The comparison is case-sensitive",
    ],
    examples: [
      { input: 'shared_letters("hello", "world")', output: "'lo'" },
      { input: 'shared_letters("banana", "band")', output: "'ban'" },
      { input: 'shared_letters("abcabc", "bc")', output: "'bc'" },
      { input: 'shared_letters("abc", "xyz")', output: "''" },
      { input: 'shared_letters("", "abc")', output: "''" },
    ],
    tests: [
      { call: 'shared_letters("hello", "world")', args: "('hello', 'world')", expected: "'lo'" },
      { call: 'shared_letters("banana", "band")', args: "('banana', 'band')", expected: "'ban'" },
      { call: 'shared_letters("abcabc", "bc")', args: "('abcabc', 'bc')", expected: "'bc'" },
      { call: 'shared_letters("abc", "xyz")', args: "('abc', 'xyz')", expected: "''" },
      { call: 'shared_letters("", "abc")', args: "('', 'abc')", expected: "''" },
      { call: 'shared_letters("abc", "")', args: "('abc', '')", expected: "''" },
      { call: 'shared_letters("aabbcc", "abc")', args: "('aabbcc', 'abc')", expected: "'abc'" },
      { call: 'shared_letters("zyx", "xy")', args: "('zyx', 'xy')", expected: "'yx'" },
      { call: 'shared_letters("ABC", "abc")', args: "('ABC', 'abc')", expected: "''" },
      { call: 'shared_letters("aab", "baa")', args: "('aab', 'baa')", expected: "'ab'" },
      { call: 'shared_letters("hello world", "o w")', args: "('hello world', 'o w')", expected: "'o w'" },
    ],
  },

  // -----------------------------------------------------------------------
  // DAY 2
  // -----------------------------------------------------------------------
  {
    id: "echo-chant",
    tier: 2,
    title: "The Pantry Echo",
    tagline: "Some labels read the same from both sides of the shelf.",
    icon: "record-voice-over",
    funcName: "echo_chant",
    topics: ["Palindrome", "Two Pointers"],
    stub: "def echo_chant(label: str) -> bool:\n    pass\n",
    story: [
      "Bob swears his pantry is haunted: some of the jar labels he wrote sound EXACTLY the same whether you read them from the left side of the shelf or the right. He calls those labels 'echoes'.",
      "Help Bob detect echoes: check if a label reads the same forwards and backwards, ignoring spaces and the difference between uppercase and lowercase letters. An empty label, Bob insists, cannot echo — there is nothing to repeat.",
    ],
    signature: "def echo_chant(label: str) -> bool:",
    rules: [
      "Check if the string reads the same forwards and backwards",
      "Ignore spaces entirely",
      "Ignore uppercase/lowercase differences",
      "An empty string is NOT an echo (return False)",
      "A single character always echoes",
    ],
    examples: [
      { input: 'echo_chant("racecar")', output: "True" },
      { input: 'echo_chant("A man a plan a canal Panama")', output: "True" },
      { input: 'echo_chant("race a car")', output: "False" },
      { input: 'echo_chant("Was it a car or a cat I saw")', output: "True" },
      { input: 'echo_chant("hello")', output: "False" },
      { input: 'echo_chant("Madam Im Adam")', output: "True" },
      { input: 'echo_chant("")', output: "False" },
    ],
    tests: [
      { call: 'echo_chant("racecar")', args: "('racecar',)", expected: "True" },
      { call: 'echo_chant("A man a plan a canal Panama")', args: "('A man a plan a canal Panama',)", expected: "True" },
      { call: 'echo_chant("race a car")', args: "('race a car',)", expected: "False" },
      { call: 'echo_chant("Was it a car or a cat I saw")', args: "('Was it a car or a cat I saw',)", expected: "True" },
      { call: 'echo_chant("hello")', args: "('hello',)", expected: "False" },
      { call: 'echo_chant("Madam Im Adam")', args: "('Madam Im Adam',)", expected: "True" },
      { call: 'echo_chant("")', args: "('',)", expected: "False" },
      { call: 'echo_chant("a")', args: "('a',)", expected: "True" },
      { call: 'echo_chant("ab")', args: "('ab',)", expected: "False" },
      { call: 'echo_chant("Never odd or even")', args: "('Never odd or even',)", expected: "True" },
      { call: 'echo_chant("A Toyota")', args: "('A Toyota',)", expected: "True" },
      { call: 'echo_chant("ab a")', args: "('ab a',)", expected: "True" },
      { call: 'echo_chant("xyz")', args: "('xyz',)", expected: "False" },
      { call: 'echo_chant("RaceCar")', args: "('RaceCar',)", expected: "True" },
    ],
  },
  {
    id: "mirror-shelves",
    tier: 2,
    title: "Mirror, Mirror, on the Shelf",
    tagline: "Bob bought a mirror. Now every shelf row looks backwards.",
    icon: "flip",
    funcName: "mirror_shelves",
    topics: ["Array Reversal", "List Comprehension"],
    stub: "def mirror_shelves(shelves: list[list[int]]) -> list[list[int]]:\n    pass\n",
    story: [
      "Bob hung a big mirror at the end of his pantry. Every shelf — a neat row of numbered jars — now appears perfectly backwards in the reflection, and Bob finds it oddly beautiful.",
      "He keeps his inventory as a list of rows, where each row is a list of jar numbers. Write the function that produces what the mirror shows: a NEW list where every row is reversed.",
    ],
    signature: "def mirror_shelves(shelves: list[list[int]]) -> list[list[int]]:",
    rules: [
      "Take a list of rows (each row a list of integers)",
      "Return a new list where each row is reversed",
      "Do not modify the original inventory",
      "Handle single jars and single rows",
      "Negative jar numbers exist (don't ask)",
    ],
    examples: [
      { input: "mirror_shelves([[1, 2, 3], [4, 5, 6]])", output: "[[3, 2, 1], [6, 5, 4]]" },
      { input: "mirror_shelves([[1, 2], [3, 4], [5, 6]])", output: "[[2, 1], [4, 3], [6, 5]]" },
      { input: "mirror_shelves([[7]])", output: "[[7]]" },
      { input: "mirror_shelves([[1, 2, 3, 4]])", output: "[[4, 3, 2, 1]]" },
      { input: "mirror_shelves([[-1, -2], [-3, -4]])", output: "[[-2, -1], [-4, -3]]" },
    ],
    tests: [
      { call: "mirror_shelves([[1, 2, 3], [4, 5, 6]])", args: "([[1, 2, 3], [4, 5, 6]],)", expected: "[[3, 2, 1], [6, 5, 4]]" },
      { call: "mirror_shelves([[1, 2], [3, 4], [5, 6]])", args: "([[1, 2], [3, 4], [5, 6]],)", expected: "[[2, 1], [4, 3], [6, 5]]" },
      { call: "mirror_shelves([[7]])", args: "([[7]],)", expected: "[[7]]" },
      { call: "mirror_shelves([[1, 2, 3, 4]])", args: "([[1, 2, 3, 4]],)", expected: "[[4, 3, 2, 1]]" },
      { call: "mirror_shelves([[-1, -2], [-3, -4]])", args: "([[-1, -2], [-3, -4]],)", expected: "[[-2, -1], [-4, -3]]" },
      { call: "mirror_shelves([])", args: "([],)", expected: "[]" },
      { call: "mirror_shelves([[], []])", args: "([[], []],)", expected: "[[], []]" },
      { call: "mirror_shelves([[0]])", args: "([[0]],)", expected: "[[0]]" },
    ],
  },

  // -----------------------------------------------------------------------
  // DAY 3
  // -----------------------------------------------------------------------
  {
    id: "hidden-word",
    tier: 3,
    title: "The Hidden Word in the Fence",
    tagline: "Is Grandma's secret word carved along the fence boards?",
    icon: "visibility-off",
    funcName: "hidden_word",
    topics: ["Subsequence Check", "Two Pointers"],
    stub: "def hidden_word(secret: str, boards: str) -> bool:\n    pass\n",
    story: [
      "Bob's grandmother hid a secret word along the garden fence: each board has one letter carved into it, and if you read the boards left to right, her word appears — in order, but not necessarily on neighboring boards. Other letters are just decoys.",
      "Given the secret word and the letters on the whole fence, check whether the secret is hidden in there: every character of the secret must appear in the fence in the same order, with any amount of decoys in between. The carving is case-sensitive — Grandma was precise.",
    ],
    signature: "def hidden_word(secret: str, boards: str) -> bool:",
    rules: [
      "Check if the secret is a subsequence of the fence letters",
      "Characters must appear in the same order, not necessarily adjacent",
      "The comparison is case-sensitive",
      "An empty secret is always hidden (return True)",
      "A secret longer than the fence can never be hidden",
    ],
    examples: [
      { input: 'hidden_word("abc", "a1b2c3")', output: "True" },
      { input: 'hidden_word("ace", "abcde")', output: "True" },
      { input: 'hidden_word("aec", "abcde")', output: "False" },
      { input: 'hidden_word("", "abc")', output: "True" },
      { input: 'hidden_word("abc", "ab")', output: "False" },
      { input: 'hidden_word("aaaa", "aaa")', output: "False" },
      { input: 'hidden_word("sing", "subsequence testing")', output: "True" },
    ],
    tests: [
      { call: 'hidden_word("abc", "a1b2c3")', args: "('abc', 'a1b2c3')", expected: "True" },
      { call: 'hidden_word("ace", "abcde")', args: "('ace', 'abcde')", expected: "True" },
      { call: 'hidden_word("aec", "abcde")', args: "('aec', 'abcde')", expected: "False" },
      { call: 'hidden_word("", "abc")', args: "('', 'abc')", expected: "True" },
      { call: 'hidden_word("", "")', args: "('', '')", expected: "True" },
      { call: 'hidden_word("abc", "ab")', args: "('abc', 'ab')", expected: "False" },
      { call: 'hidden_word("xyz", "abc")', args: "('xyz', 'abc')", expected: "False" },
      { call: 'hidden_word("aaaa", "aaa")', args: "('aaaa', 'aaa')", expected: "False" },
      { call: 'hidden_word("aab", "aaab")', args: "('aab', 'aaab')", expected: "True" },
      { call: 'hidden_word("aba", "aabb")', args: "('aba', 'aabb')", expected: "False" },
      { call: 'hidden_word("abc", "ABC")', args: "('abc', 'ABC')", expected: "False" },
      { call: 'hidden_word("sing", "subsequence testing")', args: "('sing', 'subsequence testing')", expected: "True" },
      { call: 'hidden_word("aab", "abab")', args: "('aab', 'abab')", expected: "True" },
      { call: 'hidden_word("abc", "acb")', args: "('abc', 'acb')", expected: "False" },
      { call: 'hidden_word("Ab", "aAb")', args: "('Ab', 'aAb')", expected: "True" },
      { call: 'hidden_word("abc", "ac")', args: "('abc', 'ac')", expected: "False" },
    ],
  },
  {
    id: "owl-post-code",
    tier: 3,
    title: "The Owl Post Code",
    tagline: "The owls stamp mail in weird bases. Translate for Bob.",
    icon: "numbers",
    funcName: "owl_post_code",
    topics: ["Base Conversion", "Math"],
    stub: "def owl_post_code(code: str, from_base: int, to_base: int) -> str:\n    pass\n",
    story: [
      "The village owls deliver Bob's mail, but they stamp every parcel with a number in whatever base that particular owl prefers — anywhere from base 2 to base 36. Values above 9 are written with the letters A to Z (A is 10, Z is 35).",
      "Bob needs a translator: given the stamped code, the base it was written in, and the base he wants, return the converted code as a string. If an owl stamps nonsense — a base outside 2..36, or a digit that doesn't exist in the source base — the function must return \"ERROR\" so Bob knows the owl was napping.",
    ],
    signature: "def owl_post_code(code: str, from_base: int, to_base: int) -> str:",
    rules: [
      "Convert the code from from_base to to_base, supporting bases 2 to 36",
      "Digits are 0-9 and letters A-Z (A=10 ... Z=35)",
      "Return \"ERROR\" for any invalid input (bad base, digit out of range)",
      "Return the result as a string",
      "Zero converts to \"0\" in any base",
    ],
    examples: [
      { input: 'owl_post_code("1010", 2, 10)', output: "'10'" },
      { input: 'owl_post_code("FF", 16, 10)', output: "'255'" },
      { input: 'owl_post_code("255", 10, 16)', output: "'FF'" },
      { input: 'owl_post_code("123", 10, 2)', output: "'1111011'" },
      { input: 'owl_post_code("Z", 36, 10)', output: "'35'" },
      { input: 'owl_post_code("35", 10, 36)', output: "'Z'" },
      { input: 'owl_post_code("123", 1, 10)', output: "'ERROR'", note: "base 1 is not a thing" },
      { input: 'owl_post_code("G", 16, 10)', output: "'ERROR'", note: "G is not a hex digit" },
    ],
    tests: [
      { call: 'owl_post_code("1010", 2, 10)', args: "('1010', 2, 10)", expected: "'10'" },
      { call: 'owl_post_code("FF", 16, 10)', args: "('FF', 16, 10)", expected: "'255'" },
      { call: 'owl_post_code("255", 10, 16)', args: "('255', 10, 16)", expected: "'FF'" },
      { call: 'owl_post_code("123", 10, 2)', args: "('123', 10, 2)", expected: "'1111011'" },
      { call: 'owl_post_code("Z", 36, 10)', args: "('Z', 36, 10)", expected: "'35'" },
      { call: 'owl_post_code("35", 10, 36)', args: "('35', 10, 36)", expected: "'Z'" },
      { call: 'owl_post_code("123", 1, 10)', args: "('123', 1, 10)", expected: "'ERROR'" },
      { call: 'owl_post_code("G", 16, 10)', args: "('G', 16, 10)", expected: "'ERROR'" },
      { call: 'owl_post_code("0", 10, 2)', args: "('0', 10, 2)", expected: "'0'" },
      { call: 'owl_post_code("1", 2, 10)', args: "('1', 2, 10)", expected: "'1'" },
      { call: 'owl_post_code("2", 2, 10)', args: "('2', 2, 10)", expected: "'ERROR'" },
      { call: 'owl_post_code("8", 8, 10)', args: "('8', 8, 10)", expected: "'ERROR'" },
      { call: 'owl_post_code("10", 2, 37)', args: "('10', 2, 37)", expected: "'ERROR'" },
      { call: 'owl_post_code("10", 37, 10)', args: "('10', 37, 10)", expected: "'ERROR'" },
      { call: 'owl_post_code("10", 2, 1)', args: "('10', 2, 1)", expected: "'ERROR'" },
      { call: 'owl_post_code("", 10, 2)', args: "('', 10, 2)", expected: "'ERROR'" },
      { call: 'owl_post_code("10", 10, 10)', args: "('10', 10, 10)", expected: "'10'" },
      { call: 'owl_post_code("ABC", 16, 16)', args: "('ABC', 16, 16)", expected: "'ABC'" },
      { call: 'owl_post_code("1000000", 2, 10)', args: "('1000000', 2, 10)", expected: "'64'" },
      { call: 'owl_post_code("0", 2, 36)', args: "('0', 2, 36)", expected: "'0'" },
      { call: 'owl_post_code("FFFF", 16, 10)', args: "('FFFF', 16, 10)", expected: "'65535'" },
    ],
  },
  {
    id: "staircase-digits",
    tier: 3,
    title: "Staircase Digits",
    tagline: "Count the little steps going up in Bob's combination lock.",
    icon: "stairs",
    funcName: "staircase_digits",
    topics: ["String Scanning", "Counting"],
    stub: "def staircase_digits(lock: str) -> int:\n    pass\n",
    story: [
      "Bob's shed lock is an old dial with a long scratched code. Bob, being Bob, counts 'steps' in it: a step is two ADJACENT digits where the second is exactly one greater than the first — like climbing a tiny staircase. Note that 9 followed by 0 is NOT a step; staircases don't wrap around.",
      "Given the scratched code (which may contain letters and other junk between digits), count how many steps it contains.",
    ],
    signature: "def staircase_digits(lock: str) -> int:",
    rules: [
      "Count adjacent digit pairs where the second digit is exactly the first + 1",
      "A 9 followed by a 0 does NOT count",
      "Non-digit characters simply don't form steps",
      "Only adjacent characters form pairs",
      "Handle empty strings (0 steps)",
    ],
    examples: [
      { input: 'staircase_digits("123")', output: "2", note: "12 and 23" },
      { input: 'staircase_digits("12a34")', output: "2", note: "12 and 34, the letter breaks nothing else" },
      { input: 'staircase_digits("987654321")', output: "0", note: "all going down" },
      { input: 'staircase_digits("01234567")', output: "7" },
      { input: 'staircase_digits("abc")', output: "0" },
      { input: 'staircase_digits("1a2b3c4")', output: "0", note: "nothing adjacent" },
      { input: 'staircase_digits("112233")', output: "2" },
    ],
    tests: [
      { call: 'staircase_digits("123")', args: "('123',)", expected: "2" },
      { call: 'staircase_digits("12a34")', args: "('12a34',)", expected: "2" },
      { call: 'staircase_digits("987654321")', args: "('987654321',)", expected: "0" },
      { call: 'staircase_digits("01234567")', args: "('01234567',)", expected: "7" },
      { call: 'staircase_digits("abc")', args: "('abc',)", expected: "0" },
      { call: 'staircase_digits("1a2b3c4")', args: "('1a2b3c4',)", expected: "0" },
      { call: 'staircase_digits("112233")', args: "('112233',)", expected: "2" },
      { call: 'staircase_digits("90")', args: "('90',)", expected: "0" },
      { call: 'staircase_digits("")', args: "('',)", expected: "0" },
      { call: 'staircase_digits("789")', args: "('789',)", expected: "2" },
      { call: 'staircase_digits("019")', args: "('019',)", expected: "1" },
      { call: 'staircase_digits("9")', args: "('9',)", expected: "0" },
      { call: 'staircase_digits("00")', args: "('00',)", expected: "0" },
      { call: 'staircase_digits("5a6")', args: "('5a6',)", expected: "0" },
      { call: 'staircase_digits("2345")', args: "('2345',)", expected: "3" },
      { call: 'staircase_digits("10")', args: "('10',)", expected: "0" },
    ],
  },

  // -----------------------------------------------------------------------
  // DAY 4
  // -----------------------------------------------------------------------
  {
    id: "letter-stew",
    tier: 4,
    title: "Grandma's Letter Stew",
    tagline: "Two jars of alphabet soup — same letters, different order?",
    icon: "soup-kitchen",
    funcName: "letter_stew",
    topics: ["Anagram", "Frequency Counting"],
    stub: "def letter_stew(jar_a: str, jar_b: str) -> bool:\n    pass\n",
    story: [
      "At the market, Bob sells jars of his grandma's alphabet soup. A food critic claims two jars are 'the same stew' if they contain exactly the same letters in exactly the same quantities — order doesn't matter, and nobody cares about capitals or the spaces between noodle letters.",
      "Given the letter contents of two jars, decide whether they are the same stew.",
    ],
    signature: "def letter_stew(jar_a: str, jar_b: str) -> bool:",
    rules: [
      "Both strings must contain the same letters with the same quantities",
      "Ignore spaces and uppercase/lowercase differences",
      "Order of letters does not matter",
      "Two empty jars are the same stew",
      "Different quantities of any letter means False",
    ],
    examples: [
      { input: 'letter_stew("listen", "silent")', output: "True" },
      { input: 'letter_stew("Triangle", "Integral")', output: "True" },
      { input: 'letter_stew("Dormitory", "Dirty Room")', output: "True" },
      { input: 'letter_stew("hello", "world")', output: "False" },
      { input: 'letter_stew("", "")', output: "True" },
      { input: 'letter_stew("abc", "abcc")', output: "False" },
    ],
    tests: [
      { call: 'letter_stew("listen", "silent")', args: "('listen', 'silent')", expected: "True" },
      { call: 'letter_stew("Triangle", "Integral")', args: "('Triangle', 'Integral')", expected: "True" },
      { call: 'letter_stew("Dormitory", "Dirty Room")', args: "('Dormitory', 'Dirty Room')", expected: "True" },
      { call: 'letter_stew("Astronomer", "Moon starer")', args: "('Astronomer', 'Moon starer')", expected: "True" },
      { call: 'letter_stew("hello", "world")', args: "('hello', 'world')", expected: "False" },
      { call: 'letter_stew("test", "ttew")', args: "('test', 'ttew')", expected: "False" },
      { call: 'letter_stew("abc", "abcc")', args: "('abc', 'abcc')", expected: "False" },
      { call: 'letter_stew("", "")', args: "('', '')", expected: "True" },
      { call: 'letter_stew("a gentleman", "elegant man")', args: "('a gentleman', 'elegant man')", expected: "True" },
      { call: 'letter_stew("aabb", "ab")', args: "('aabb', 'ab')", expected: "False" },
      { call: 'letter_stew("aab", "aba")', args: "('aab', 'aba')", expected: "True" },
      { call: 'letter_stew("ab", "a b")', args: "('ab', 'a b')", expected: "True" },
      { call: 'letter_stew("aAb", "AbA")', args: "('aAb', 'AbA')", expected: "True" },
      { call: 'letter_stew("abc", "abcd")', args: "('abc', 'abcd')", expected: "False" },
      { call: 'letter_stew("aab", "abb")', args: "('aab', 'abb')", expected: "False" },
    ],
  },
  {
    id: "merge-harvest-rows",
    tier: 4,
    title: "Merging the Harvest Rows",
    tagline: "Two sorted crates of apples, one master crate.",
    icon: "merge",
    funcName: "merge_harvest_rows",
    topics: ["Merge Sorted Arrays", "Two Pointers"],
    stub: "def merge_harvest_rows(crate_a: list[int], crate_b: list[int]) -> list[int]:\n    pass\n",
    story: [
      "Bob sells apples by weight, and each crate is already arranged from the lightest apple to the heaviest. At the market stall he needs ONE master crate: two customers' crates merged together, still perfectly ordered.",
      "Given the two crates (each sorted in ascending order), return a single merged list in ascending order. Both crates may hold apples of identical weight — keep them all.",
      "One more thing: Bob's robot helper is watching, and it will REFUSE to grade any solution that uses sorted(), list.sort(), or heapq.merge(). Bob says the whole point is to merge already-sorted crates by hand — re-sorting everything is cheating.",
    ],
    signature: "def merge_harvest_rows(crate_a: list[int], crate_b: list[int]) -> list[int]:",
    rules: [
      "Both input lists are sorted in ascending order",
      "Return one merged list, also in ascending order",
      "Keep all duplicates",
      "Handle empty crates",
      "The inputs must not be modified",
      "FORBIDDEN: using sorted(), list.sort(), or heapq.merge() — the robot checks and rejects them",
    ],
    banned: { names: ["sorted", "merge"], attrs: ["sort", "merge"] },
    examples: [
      { input: "merge_harvest_rows([1, 3, 5], [2, 4, 6])", output: "[1, 2, 3, 4, 5, 6]" },
      { input: "merge_harvest_rows([1, 2, 3], [4, 5, 6])", output: "[1, 2, 3, 4, 5, 6]" },
      { input: "merge_harvest_rows([1], [2, 3, 4])", output: "[1, 2, 3, 4]" },
      { input: "merge_harvest_rows([], [1, 2, 3])", output: "[1, 2, 3]" },
      { input: "merge_harvest_rows([1, 1, 2], [1, 3, 3])", output: "[1, 1, 1, 2, 3, 3]" },
    ],
    tests: [
      { call: "merge_harvest_rows([1, 3, 5], [2, 4, 6])", args: "([1, 3, 5], [2, 4, 6])", expected: "[1, 2, 3, 4, 5, 6]" },
      { call: "merge_harvest_rows([1, 2, 3], [4, 5, 6])", args: "([1, 2, 3], [4, 5, 6])", expected: "[1, 2, 3, 4, 5, 6]" },
      { call: "merge_harvest_rows([1], [2, 3, 4])", args: "([1], [2, 3, 4])", expected: "[1, 2, 3, 4]" },
      { call: "merge_harvest_rows([], [1, 2, 3])", args: "([], [1, 2, 3])", expected: "[1, 2, 3]" },
      { call: "merge_harvest_rows([1, 1, 2], [1, 3, 3])", args: "([1, 1, 2], [1, 3, 3])", expected: "[1, 1, 1, 2, 3, 3]" },
      { call: "merge_harvest_rows([], [])", args: "([], [])", expected: "[]" },
      { call: "merge_harvest_rows([5], [5])", args: "([5], [5])", expected: "[5, 5]" },
      { call: "merge_harvest_rows([-3, 0], [-2, -1])", args: "([-3, 0], [-2, -1])", expected: "[-3, -2, -1, 0]" },
      { call: "merge_harvest_rows([2, 4], [1, 3, 5])", args: "([2, 4], [1, 3, 5])", expected: "[1, 2, 3, 4, 5]" },
      { call: "merge_harvest_rows([1, 2, 2], [2, 2])", args: "([1, 2, 2], [2, 2])", expected: "[1, 2, 2, 2, 2]" },
    ],
  },
  {
    id: "scrabble-rack",
    tier: 4,
    title: "The Scrabble Rack Swap",
    tagline: "Did the magpie just rearrange Bob's tiles, or steal some?",
    icon: "grid-on",
    funcName: "scrabble_rack",
    topics: ["Permutation Check", "Frequency Counting"],
    stub: "def scrabble_rack(before: str, after: str) -> bool:\n    pass\n",
    story: [
      "Bob plays scrabble on the porch, and a cheeky magpie keeps hopping onto the table. Afterwards Bob wonders: did the bird merely shuffle his tile rack around, or did it actually steal a tile and leave a fake?",
      "Given the rack before and after the magpie's visit, decide if the second string is an exact rearrangement of the first. Every character counts here — capitals, spaces and punctuation are all distinct tiles in Bob's deluxe edition. Two empty racks, of course, are identical.",
    ],
    signature: "def scrabble_rack(before: str, after: str) -> bool:",
    rules: [
      "Check if the two strings are permutations of each other",
      "Case-sensitive: 'A' and 'a' are different tiles",
      "Spaces and punctuation count as regular characters",
      "Empty strings are permutations of each other",
      "Different lengths always means False",
    ],
    examples: [
      { input: 'scrabble_rack("abc", "bca")', output: "True" },
      { input: 'scrabble_rack("abc", "def")', output: "False" },
      { input: 'scrabble_rack("listen", "silent")', output: "True" },
      { input: 'scrabble_rack("hello", "bello")', output: "False" },
      { input: 'scrabble_rack("", "")', output: "True" },
      { input: 'scrabble_rack("a", "")', output: "False" },
      { input: 'scrabble_rack("Abc", "abc")', output: "False" },
      { input: 'scrabble_rack("a gentleman", "elegant man")', output: "True" },
    ],
    tests: [
      { call: 'scrabble_rack("abc", "bca")', args: "('abc', 'bca')", expected: "True" },
      { call: 'scrabble_rack("abc", "def")', args: "('abc', 'def')", expected: "False" },
      { call: 'scrabble_rack("listen", "silent")', args: "('listen', 'silent')", expected: "True" },
      { call: 'scrabble_rack("hello", "bello")', args: "('hello', 'bello')", expected: "False" },
      { call: 'scrabble_rack("", "")', args: "('', '')", expected: "True" },
      { call: 'scrabble_rack("a", "")', args: "('a', '')", expected: "False" },
      { call: 'scrabble_rack("Abc", "abc")', args: "('Abc', 'abc')", expected: "False" },
      { call: 'scrabble_rack("a gentleman", "elegant man")', args: "('a gentleman', 'elegant man')", expected: "True" },
      { call: 'scrabble_rack("aab", "aba")', args: "('aab', 'aba')", expected: "True" },
      { call: 'scrabble_rack("ab ", "ab")', args: "('ab ', 'ab')", expected: "False" },
      { call: 'scrabble_rack("a b", "ba ")', args: "('a b', 'ba ')", expected: "True" },
      { call: 'scrabble_rack("abc", "abcd")', args: "('abc', 'abcd')", expected: "False" },
    ],
  },

  // -----------------------------------------------------------------------
  // DAY 5
  // -----------------------------------------------------------------------
  {
    id: "zigzag-paint",
    tier: 5,
    title: "Zigzag Fence Painting",
    tagline: "Bob paints letters on the fence in alternating 'cases'.",
    icon: "format-paint",
    funcName: "zigzag_paint",
    topics: ["String Manipulation", "Case Handling"],
    stub: "def zigzag_paint(phrase: str) -> str:\n    pass\n",
    story: [
      "Bob is painting a welcome phrase on the fence in his signature zigzag style: the first letter lowercase, the second UPPERCASE, the third lowercase, and so on. Digits, punctuation and other decorations stay as they are and do NOT advance the zigzag rhythm.",
      "There's one quirk: a space repaints the rhythm from scratch — the next letter after a space always starts lowercase again. Given the phrase Bob wants to paint, return it in zigzag style.",
    ],
    signature: "def zigzag_paint(phrase: str) -> str:",
    rules: [
      "Alternate letter case: lowercase, uppercase, lowercase...",
      "Only alphabetic characters change and count in the alternation",
      "Non-alphabetic characters stay unchanged and do not advance the rhythm",
      "A space resets the rhythm (next letter is lowercase again)",
      "Handle empty phrases",
    ],
    examples: [
      { input: 'zigzag_paint("hello")', output: "'hElLo'" },
      { input: 'zigzag_paint("Hello World")', output: "'hElLo wOrLd'", note: "the space restarts the rhythm" },
      { input: 'zigzag_paint("abc123def")', output: "'aBc123DeF'" },
      { input: 'zigzag_paint("Python3.9!")', output: "'pYtHoN3.9!'" },
      { input: 'zigzag_paint("")', output: "''" },
    ],
    tests: [
      { call: 'zigzag_paint("hello")', args: "('hello',)", expected: "'hElLo'" },
      { call: 'zigzag_paint("Hello World")', args: "('Hello World',)", expected: "'hElLo wOrLd'" },
      { call: 'zigzag_paint("abc123def")', args: "('abc123def',)", expected: "'aBc123DeF'" },
      { call: 'zigzag_paint("Python3.9!")', args: "('Python3.9!',)", expected: "'pYtHoN3.9!'" },
      { call: 'zigzag_paint("")', args: "('',)", expected: "''" },
      { call: 'zigzag_paint("a")', args: "('a',)", expected: "'a'" },
      { call: 'zigzag_paint("AB")', args: "('AB',)", expected: "'aB'" },
      { call: 'zigzag_paint("hi  there")', args: "('hi  there',)", expected: "'hI  tHeRe'" },
      { call: 'zigzag_paint("123")', args: "('123',)", expected: "'123'" },
      { call: 'zigzag_paint("a1b")', args: "('a1b',)", expected: "'a1B'" },
      { call: 'zigzag_paint("a b c")', args: "('a b c',)", expected: "'a b c'" },
      { call: 'zigzag_paint("HELLO")', args: "('HELLO',)", expected: "'hElLo'" },
    ],
  },
  {
    id: "weather-vane-spin",
    tier: 5,
    title: "The Weather Vane Spin",
    tagline: "A gust spun Bob's weather vane k clicks to the right.",
    icon: "rotate-right",
    funcName: "weather_vane_spin",
    topics: ["Array Rotation", "Modulo Arithmetic"],
    stub: "def weather_vane_spin(markers: list[int], k: int) -> list[int]:\n    pass\n",
    story: [
      "Bob's weather vane is a ring painted with numbered markers. Last night's gust spun it k clicks to the right: the last k markers swung around to the front, keeping their order.",
      "Given the markers as Bob recorded them before the gust and the number of clicks k, return how the ring reads now. The gust can be stronger than the ring is long — spinning a 3-marker ring by 3 clicks just brings it home.",
      "One more thing: Bob's robot helper is watching, and it will REFUSE to grade any solution that uses deque.rotate(). Bob says the wrapping is the whole puzzle — let the modulo do the talking.",
    ],
    signature: "def weather_vane_spin(markers: list[int], k: int) -> list[int]:",
    rules: [
      "Rotate the list to the right by k positions",
      "The last k elements move to the front, keeping their order",
      "k can be larger than the list length (it wraps around)",
      "k can be 0 (nothing moves)",
      "Handle empty rings",
      "FORBIDDEN: using deque.rotate() — the robot checks and rejects it",
    ],
    banned: { attrs: ["rotate"] },
    examples: [
      { input: "weather_vane_spin([1, 2, 3, 4, 5], 2)", output: "[4, 5, 1, 2, 3]" },
      { input: "weather_vane_spin([1, 2, 3], 1)", output: "[3, 1, 2]" },
      { input: "weather_vane_spin([1, 2, 3, 4], 0)", output: "[1, 2, 3, 4]" },
      { input: "weather_vane_spin([1, 2, 3], 5)", output: "[2, 3, 1]", note: "5 clicks on 3 markers = 2 real clicks" },
      { input: "weather_vane_spin([], 3)", output: "[]" },
    ],
    tests: [
      { call: "weather_vane_spin([1, 2, 3, 4, 5], 2)", args: "([1, 2, 3, 4, 5], 2)", expected: "[4, 5, 1, 2, 3]" },
      { call: "weather_vane_spin([1, 2, 3], 1)", args: "([1, 2, 3], 1)", expected: "[3, 1, 2]" },
      { call: "weather_vane_spin([1, 2, 3, 4], 0)", args: "([1, 2, 3, 4], 0)", expected: "[1, 2, 3, 4]" },
      { call: "weather_vane_spin([1, 2, 3], 5)", args: "([1, 2, 3], 5)", expected: "[2, 3, 1]" },
      { call: "weather_vane_spin([], 3)", args: "([], 3)", expected: "[]" },
      { call: "weather_vane_spin([1], 1)", args: "([1], 1)", expected: "[1]" },
      { call: "weather_vane_spin([1, 2], 4)", args: "([1, 2], 4)", expected: "[1, 2]" },
      { call: "weather_vane_spin([1, 2, 3, 4], 4)", args: "([1, 2, 3, 4], 4)", expected: "[1, 2, 3, 4]" },
      { call: "weather_vane_spin([1, 2, 3, 4, 5], 7)", args: "([1, 2, 3, 4, 5], 7)", expected: "[4, 5, 1, 2, 3]" },
      { call: "weather_vane_spin([9, 8], 3)", args: "([9, 8], 3)", expected: "[8, 9]" },
    ],
  },

  // -----------------------------------------------------------------------
  // DAY 6
  // -----------------------------------------------------------------------
  {
    id: "nesting-boxes",
    tier: 1,
    title: "The Nesting Gift Boxes",
    tagline: "Every box Bob opens must close in the right order.",
    icon: "inventory",
    funcName: "nesting_boxes",
    topics: ["Valid Parentheses", "Stack"],
    stub: "def nesting_boxes(tags: str) -> bool:\n    pass\n",
    story: [
      "Bob wraps presents in nesting boxes of three shapes: round (), square [] and curly {}. His label printer tags each gift with a string of marks — one per box rim, in the order the rims meet. A gift only stacks properly if every opening mark is matched by a closing mark of the same shape, in the correct nesting order. Any stray letters on the tag are just the gift shop's stamp and can be ignored.",
      "Given the tag string, decide whether the boxes nest correctly.",
    ],
    signature: "def nesting_boxes(tags: str) -> bool:",
    rules: [
      "Brackets come in three shapes: (), [] and {}",
      "Every opening bracket needs a matching closing bracket of the same shape",
      "Brackets must close in the correct nesting order",
      "Other characters in the string are irrelevant",
      "An empty tag nests perfectly (return True)",
    ],
    examples: [
      { input: 'nesting_boxes("()")', output: "True" },
      { input: 'nesting_boxes("()[]{}")', output: "True" },
      { input: 'nesting_boxes("(]")', output: "False" },
      { input: 'nesting_boxes("([)]")', output: "False" },
      { input: 'nesting_boxes("{[]}")', output: "True" },
      { input: 'nesting_boxes("hello(world)")', output: "True", note: "letters are just stamps" },
      { input: 'nesting_boxes("((())")', output: "False" },
      { input: 'nesting_boxes("")', output: "True" },
    ],
    tests: [
      { call: 'nesting_boxes("()")', args: "('()',)", expected: "True" },
      { call: 'nesting_boxes("()[]{}")', args: "('()[]{}',)", expected: "True" },
      { call: 'nesting_boxes("(]")', args: "('(]',)", expected: "False" },
      { call: 'nesting_boxes("([)]")', args: "('([)]',)", expected: "False" },
      { call: 'nesting_boxes("{[]}")', args: "('{[]}',)", expected: "True" },
      { call: 'nesting_boxes("hello(world)[test]{code}")', args: "('hello(world)[test]{code}',)", expected: "True" },
      { call: 'nesting_boxes("((()))")', args: "('((()))',)", expected: "True" },
      { call: 'nesting_boxes("((())")', args: "('((())',)", expected: "False" },
      { call: 'nesting_boxes("")', args: "('',)", expected: "True" },
      { call: 'nesting_boxes("[")', args: "('[',)", expected: "False" },
      { call: 'nesting_boxes("}{")', args: "('}{',)", expected: "False" },
      { call: 'nesting_boxes(")(")', args: "(')(',)", expected: "False" },
      { call: 'nesting_boxes("(((")', args: "('(((',)", expected: "False" },
      { call: 'nesting_boxes("{[}]")', args: "('{[}]',)", expected: "False" },
      { call: 'nesting_boxes("a{b[c]d}e")', args: "('a{b[c]d}e',)", expected: "True" },
      { call: 'nesting_boxes("]")', args: "(']',)", expected: "False" },
      { call: 'nesting_boxes("([{}])")', args: "('([{}])',)", expected: "True" },
    ],
  },
  {
    id: "scarecrow-whisper",
    tier: 6,
    title: "Whispers for the Scarecrow",
    tagline: "Bob encodes the scarecrow's orders with an old letter shift.",
    icon: "hearing",
    funcName: "scarecrow_whisper",
    topics: ["Caesar Cipher", "ASCII Math"],
    stub: "def scarecrow_whisper(order: str, shift: int) -> str:\n    pass\n",
    story: [
      "Bob is convinced his scarecrow understands instructions — as long as they're whispered in code. His code is the oldest one around: every letter slides forward in the alphabet by a fixed shift, wrapping from Z back to A. A negative shift slides letters backwards instead. Digits, spaces and punctuation stay untouched — the scarecrow only cares about letters.",
      "Given the plain order and the shift, return the whispered version. Capital letters stay capital, lowercase stay lowercase.",
    ],
    signature: "def scarecrow_whisper(order: str, shift: int) -> str:",
    rules: [
      "Shift every letter forward by shift positions in the alphabet",
      "The alphabet wraps around (z shifted by 3 becomes c)",
      "Negative shifts slide letters backwards",
      "Uppercase letters remain uppercase, lowercase remain lowercase",
      "Non-alphabetic characters remain unchanged",
      "Handle empty orders",
    ],
    examples: [
      { input: 'scarecrow_whisper("hello", 3)', output: "'khoor'" },
      { input: 'scarecrow_whisper("Hello World!", 1)', output: "'Ifmmp Xpsme!'" },
      { input: 'scarecrow_whisper("xyz", 3)', output: "'abc'" },
      { input: 'scarecrow_whisper("ABC123def", 5)', output: "'FGH123ijk'" },
      { input: 'scarecrow_whisper("", 10)', output: "''" },
      { input: 'scarecrow_whisper("abc", -3)', output: "'xyz'" },
    ],
    tests: [
      { call: 'scarecrow_whisper("hello", 3)', args: "('hello', 3)", expected: "'khoor'" },
      { call: 'scarecrow_whisper("Hello World!", 1)', args: "('Hello World!', 1)", expected: "'Ifmmp Xpsme!'" },
      { call: 'scarecrow_whisper("xyz", 3)', args: "('xyz', 3)", expected: "'abc'" },
      { call: 'scarecrow_whisper("ABC123def", 5)', args: "('ABC123def', 5)", expected: "'FGH123ijk'" },
      { call: 'scarecrow_whisper("", 10)', args: "('', 10)", expected: "''" },
      { call: 'scarecrow_whisper("abc", -3)', args: "('abc', -3)", expected: "'xyz'" },
      { call: 'scarecrow_whisper("abc", 0)', args: "('abc', 0)", expected: "'abc'" },
      { call: 'scarecrow_whisper("abc", 26)', args: "('abc', 26)", expected: "'abc'" },
      { call: 'scarecrow_whisper("Zz", 1)', args: "('Zz', 1)", expected: "'Aa'" },
      { call: 'scarecrow_whisper("xyz", -3)', args: "('xyz', -3)", expected: "'uvw'" },
      { call: 'scarecrow_whisper("abc", 52)', args: "('abc', 52)", expected: "'abc'" },
      { call: 'scarecrow_whisper("Hello", -1)', args: "('Hello', -1)", expected: "'Gdkkn'" },
      { call: 'scarecrow_whisper("abc", -29)', args: "('abc', -29)", expected: "'xyz'" },
    ],
  },
];

export function getExercise(id) {
  return EXERCISES.find((ex) => ex.id === id) || null;
}
